<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    
    <li>
        <label for="<?php echo $_code ?>_account_holder" class="required"><em>*</em><?php echo $this->__('Account holder:') ?></label>
        <span class="input-box">
            <input type="text" title="<?php echo $this->__('Account holder:') ?>" class="input-text required-entry" id="<?php echo $_code ?>_account_holder" name="payment[account_holder]"/>
        </span>
    </li>
    
    <li>
        <label for="<?php echo $_code ?>_account_number" class="required"><em>*</em><?php echo $this->__('IBAN:') ?></label>
        <span class="input-box">
            <input type="text" title="<?php echo $this->__('IBAN:') ?>" class="input-text required-entry" id="<?php echo $_code ?>_account_number" name="payment[iban]"/>
        </span>
    </li>

    <li>
        <label for="<?php echo $_code ?>_bank_code"><?php echo $this->__('Bank code (BIC/SWIFT)') ?></label>
        <span class="input-box">
            <input type="text" title="<?php echo $this->__('Bank code (BIC/SWIFT)') ?>" class="input-text" id="<?php echo $_code ?>_bank_code" name="payment[bic]"/>
        </span>
    </li>
    
    <li>
        <label for="<?php echo $_code ?>_account_country" class="required"><em>*</em><?php echo $this->__('Account country:') ?></label>
        <span class="input-box">
            <select title="<?php echo $this->__('Account country:') ?>" class="select required-entry" id="<?php echo $_code ?>_account_country" name="payment[account_country]">
                <option value=""></option>
                <?php
                $countries = Mage::getStoreConfig('payment/paylanedirectdebit/account_country');

                if (false !== strpos($countries, "AT"))
                {
                ?>
                <option value="AT">Austria</option>
                <?php 
                }
                
                if (false !== strpos($countries, "DE"))
                {
                ?>
                <option value="DE">Germany</option>
                <?php 
                }
                
                if (false !== strpos($countries, "NL"))
                {
                ?>
                <option value="NL">Netherlands</option>
                <?php 
                }
                ?>
            </select>
        </span>
    </li>
</ul>
